language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jmtrieu-github"
    token:
      secure: "50e475304609cf9a8da142f0731e6cc489e3fcb1"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'